### ISSUE TITLE
Quest Population Con-Troll

### ISSUE THREAD

**Issue by Normonder** [HellscreamWoW/Tracker#1627]
http://www.wowhead.com/quest=26751/population-con-troll

when I killed beastmaster still have 0/1
when I killed mystic still have 0/7

**Comment by Malae1** [comment]
Tested, was not able to reproduce.

**Comment by GeneralCaveman** [comment]
Did you relog after you killed some trolls? Because this sounds a lot like the visual bug with quests where they visually reset after logging. Since the server knows you completed an objective it doesn't add one more kill after killing one of those mobs.

Try completing the other parts of the quest and try to turn it in or discarding, picking up the quest again.
