### ISSUE TITLE
Blackrock Spy

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#197]
"When you attack this mob and then you run off, and the mob stops attacking you and goes back to his place as a pawn, I mean without moving his legs. :)

http://www.wowhead.com/npc=49874/blackrock-spy"

**Comment by Max-Hellscream** [comment]
Unable to reproduce.

**Comment by phikaro** [comment]
You can reproduce it, by agro a Blackrock Spy and instead of attacking him, try to run away from the fight and after that when he stops chasing you he will return to his location, instead of walking to his location he will move the way he is when his spying while not attacking.

Here's screenshots:
http://store.picbg.net/pubpic/28/9E/25627cf57f72289e.jpg

http://store.picbg.net/pubpic/7A/14/bca5f367ed167a14.jpg
