### ISSUE TITLE
Quest: Never Again!

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3355]
The cavernous area I am going through has no MOBs, only 1 of 2 quest bosses is present. The quest boss Gorganonnon is not here. Also the orcish/demon village at the entrance of this cave leading to the underground cavern area is completely empty of MOBS as well, or whatever is supposed to be inhabitating the village. Let's say Village People.
![wowscrnshot_103015_213507](https://cloud.githubusercontent.com/assets/15259298/10861183/3a66280a-7f4e-11e5-847d-113379a1d0a7.jpg)

**Comment by Klickeazy** [comment]
Dont know if this was fixed after the issue was opened but both boss mobs are present. It is possible to obtain both quest items.
http://www.wowhead.com/quest=26445/never-again#see-also
Both are in different locations and do drop the quest items for quest completion. Quest can also be turned in. But the location of Diathorus The Seeker [ http://www.wowhead.com/npc=6072 ] lacks any other NPCS
