### ISSUE TITLE
Druid gyph: Acuatic form

### ISSUE THREAD

**Issue by Djurdjevdan** [HellscreamWoW/Tracker#3704]
Dosen't increase 50% speed in aquatic form.

**Comment by carminejackal** [comment]
Actually it's working: 
![](http://i.imgur.com/ZSIVJgj.png)

(Base swimming speed is 66%)

Aquatic Form increases swim speed by 50%. Take note that this 50% increase is of the 66.6% base swim speed, hence giving a 33.3% bonus. Thus the net effect of this form is to allow you to move at 100% normal running speed, in water.

Since this glyph uses the same wording as Aquatic Form, it's likely that it works in the same way too, making AF give a total bonus of 100% to the 66% base swim speed, and ending up at 133% (or 135% as seen above.)
