### ISSUE TITLE
Herbalism stopped leveling up

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#469]
Herbalism is 181 and no matter how many herbs I collect, it won't level up

**Comment by EPS1L0N** [comment]
ref #442

**Comment by Reloque** [comment]
I'm not sure why this is closed. Maybe it was a much older and slightly unrelated bug from the issue tracker... oh well.

Since around 01.05.29, I have been unable to skill up herbalism at all. Something broke, now I receive "Skill not high enough" on Earthroot/Peacebloom/Silverleaf with a new character (tested again today). This has been mentioned in the forums, but no blue posts on [that thread](http://www.hellscream-wow.com/forum/viewtopic.php?f=28&t=732&start=50) since then.

By the way, with WoD you should <s>never</s> rarely receive "skill not high enough" with herbalism. If you know the colors from [this list](http://wow.gamepedia.com/Herb), anything above orange (aka. red) should give a skillup just like orange but yields one or more [petals](http://www.wowhead.com/items=7.9?filter=maxle=99;cr=166;crs=6;crv=0) instead of the full herb (sometimes you get a full herb and petals, see [here](http://www.wow-professions.com/news/patch-53-herbalism-and-mining-changes)).
